name: ssru

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ssru
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: ssru
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4:latest 
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: P@ssw0rd
    ports:
      - "8080:80" 
    networks:
      - pg-network

volumes:
  pgdata:

networks:
  pg-network:
    driver: bridge
