import { Inter, Kanit } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const kanit = Kanit({
  subsets: ["latin", "thai"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-kanit",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`
          ${inter.variable}
          ${kanit.variable}
          antialiased bg-white text-black
        `}
        style={{
          fontFamily: "var(--font-inter), var(--font-kanit), sans-serif",
        }}
      >
        {children}
      </body>
    </html>
  );
}
