### Create category
POST http://localhost:3000/api/categories
Content-Type: application/json

{
    "name": "Hall of fame"
}

### Get categories
GET http://localhost:3000/api/categories/

### Get a category
GET http://localhost:3000/api/categories/สนทนาบนเส้นทางงาน
 

### Create category in production
POST https://kcc-uat.ssru.ac.th/api/categories
{
    "name": "สนทนาบนเส้นทางงาน",
    "slug": "career-path-conversations"
}