### Create user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Yuji Itatori",
  "email": "y.itatori@gmail.com",
  "password": "123456",
  "role": "author"
}


### Get all users
GET http://localhost:3000/api/users


### Create user in production
POST https://kcc-uat.ssru.ac.th/api/users
Content-Type: application/json

{
  "name": "Super Admin",
  "email": "admin@gmail.com",
  "password": "123456",
  "role": "admin"
}

### Get users in production
GET https://kcc-uat.ssru.ac.th/api/users